'use strict';
/** This file was autogenerated by gulp task i18n-autogenerate **/
angular
  .module('crosswatch')
  .constant('translationList', [
    {key: "de", language: "Deutsch", dir: "ltr"},
    {key: "en", language: "English", dir: "ltr"},
    {key: "pt", language: "português", dir: "ltr"},
  ]
);